### ISSUE TITLE
What do you think about this device?

### ISSUE THREAD

**Issue by tecufanujacu** [150balbes/Amlogic_s905#10]
@150balbes, as first thing excuse me for opening this non real issue but I'd like to know a your opinion about this device: [Zoomtak T8U](http://www.zoomtak.net/product-item/streaming-media-player-amlogic-s905-t8u/)

Seems to me a really interesting s905 device, specially because it has an internal sata slot to connect a 2,5" hdd or ssd and [it is not really expensive](https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20170831052350&SearchText=Zoomtak+t8u).

I'm considering to buy it to install armbian with debian server and to use it as a little nas. In my idea I'd like to install armbian in the internal emmc and use an hard disk and a microsd for the data.

Do you think that will be possible use it for this? Will works everythings as sata, wifi and bt? And what about controlling the frontal display from armbian?

Thanks in advance.

**Comment by 150balbes** [comment]
Hi.I have no available model on which You write, so I can only assume, by analogy with the Tronsmart Vega S95 Telos (the model I have in stock). In Telos uses a special system on SATA power, through activation of the GPIO port. This system of power works in Android. I was not able to obtain from the manufacturer the GPIO settings to use SATA with Linux. Therefore, it is necessary to be careful with such models. Maybe in Your model activation SATA works differently. But I strongly recommend that you pre-check with the manufacturer of this model, he can provide You with all necessary data, to use SATA in Linux.01.09.2017, 16:37, "tecufanujacu" <notifications@github.com>:@150balbes, as first thing excuse me for opening this non real issue but I'd like to know a your opinion about this device: Zoomtak T8U
Seems to me a really interesting s905 device, specially because it has an internal sata slot to connect a 2,5" hdd or ssd and it is not really expensive.
I'm considering to buy it to install armbian with debian server and to use it as a little nas. In my idea I'd like to install armbian in the internal emmc and use the an hard disk and a microsd for the data.
Do you think that will be possible use it for this? Will works everythings as wifi and bt?
Thanks in advance.

**Comment by tecufanujacu** [comment]
Thanks for answering to me.
I wrote to the manufacturer and I hope that they will answer me, obviously I'll report here their eventually answer.

Anyway can you suggest me a s905 device totally working with armbian?

A little OT, searching for some low-cost device with a built in 2,5 slot I also found an x86 device powered by an Intel Cherry Trail Z8300: [NexBox T11](http://www.inexbox.com/product-overview-of-nexbox-t11-mini-pc/)

Also this device [isn't really expensive ](https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20170903014825&SearchText=mini+pc+t11) but seems that [there are problems with the wifi on linux](https://www.amazon.com/forum/-/Tx18VNV4EFJ4JA9/ref=ask_dp_dpmw_al_hza?asin=B06VW53L88). In Amazon is reported that the wifi adapter is an AP6212 that is used a lot in arm devices as banana pi and amlogic, do you know this wifi adapter? Do you think that can it be used with debian?
Sorry for this totally OT question.

**Comment by 150balbes** [comment]
If You don't necessarily need architecture aarch64 (ARMv8), then, for Your conditions (full support Armbian + high speed connecting external drives via SATA) I suggest to explore this option. 

https://forum.armbian.com/index.php?/topic/4983-odroid-hc1/&tab=comments#comment-38639


On these models the Windows operating system. I know the point of this OS, so not when I will not recommend its use. And the ratio of the costs\of the result, these options, lose very much of the present equipment based on ARM.
